title: Nursery Handbook
author: Kevin Kubeck
logo: images/logo.png

html:
  baseurl: /nursery-manual
  use_jupyter_widgets: true  # ipywidgets output

execute:
  execute_notebooks: force  # or 'auto' if you don't want to re-run every time

bibtex_bibfiles:
  - references.bib

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  thebe: true
  binderhub_url: "https://mybinder.org"

thebe_config:
  repository_url: "https://github.com/Kkubeck/nursery-manual"
  repository_branch: "main"

interactive:
  interactive_output: true

